-- TIỆM ẢNH CAPY - SHARED DATABASE
-- Run this entire file in Supabase SQL Editor.

create table if not exists public.cameras (
  id bigint primary key,
  name text not null,
  brand text not null default '',
  type text not null default 'Máy ảnh',
  price numeric not null default 0,
  long_rates jsonb not null default '{}'::jsonb,
  hourly_rates jsonb not null default '{}'::jsonb,
  lens text not null default '',
  desc text not null default '',
  image text not null default '',
  available boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.samples (
  id uuid primary key,
  src text not null,
  description text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.plans (
  id text primary key,
  title text not null,
  price numeric not null default 0,
  note text not null default '',
  badge text not null default '',
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.policies (
  num text primary key,
  title text not null,
  text text not null default '',
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.settings (
  id integer primary key default 1,
  name text not null default 'Tiệm Ảnh Capy',
  phone text not null default '',
  zalo text not null default '#',
  facebook text not null default '#',
  address text not null default 'Bàu Tró, Quảng Trị',
  contact_title text not null default 'Nhắn Capy để',
  contact_italic text not null default 'giữ máy.',
  contact_subtext text not null default 'Hotline / Zalo',
  qr_image text not null default '',
  hero_image text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  camera_id bigint references public.cameras(id) on delete set null,
  camera text not null default '',
  plan text not null default '1-day',
  customer jsonb not null default '{}'::jsonb,
  status text not null default 'Mới',
  created_at timestamptz not null default now()
);

alter table public.cameras enable row level security;
alter table public.samples enable row level security;
alter table public.plans enable row level security;
alter table public.policies enable row level security;
alter table public.settings enable row level security;
alter table public.orders enable row level security;

-- Public website can read catalogue/content.
drop policy if exists "public read cameras" on public.cameras;
create policy "public read cameras" on public.cameras for select using (true);
drop policy if exists "admin write cameras" on public.cameras;
create policy "admin write cameras" on public.cameras for all to authenticated using (true) with check (true);

drop policy if exists "public read samples" on public.samples;
create policy "public read samples" on public.samples for select using (true);
drop policy if exists "admin write samples" on public.samples;
create policy "admin write samples" on public.samples for all to authenticated using (true) with check (true);

drop policy if exists "public read plans" on public.plans;
create policy "public read plans" on public.plans for select using (true);
drop policy if exists "admin write plans" on public.plans;
create policy "admin write plans" on public.plans for all to authenticated using (true) with check (true);

drop policy if exists "public read policies" on public.policies;
create policy "public read policies" on public.policies for select using (true);
drop policy if exists "admin write policies" on public.policies;
create policy "admin write policies" on public.policies for all to authenticated using (true) with check (true);

drop policy if exists "public read settings" on public.settings;
create policy "public read settings" on public.settings for select using (true);
drop policy if exists "admin write settings" on public.settings;
create policy "admin write settings" on public.settings for all to authenticated using (true) with check (true);

-- Customers can create booking requests, but only admins can read them.
drop policy if exists "public create orders" on public.orders;
create policy "public create orders" on public.orders for insert to anon, authenticated with check (true);
drop policy if exists "admin read orders" on public.orders;
create policy "admin read orders" on public.orders for select to authenticated using (true);
drop policy if exists "admin update orders" on public.orders;
create policy "admin update orders" on public.orders for update to authenticated using (true) with check (true);
drop policy if exists "admin delete orders" on public.orders;
create policy "admin delete orders" on public.orders for delete to authenticated using (true);

-- Storage bucket for admin-uploaded images.
insert into storage.buckets (id, name, public)
values ('capy-images', 'capy-images', true)
on conflict (id) do update set public = true;

drop policy if exists "public view capy images" on storage.objects;
create policy "public view capy images" on storage.objects for select using (bucket_id = 'capy-images');
drop policy if exists "admin upload capy images" on storage.objects;
create policy "admin upload capy images" on storage.objects for insert to authenticated with check (bucket_id = 'capy-images');
drop policy if exists "admin update capy images" on storage.objects;
create policy "admin update capy images" on storage.objects for update to authenticated using (bucket_id = 'capy-images') with check (bucket_id = 'capy-images');
drop policy if exists "admin delete capy images" on storage.objects;
create policy "admin delete capy images" on storage.objects for delete to authenticated using (bucket_id = 'capy-images');

-- Availability checks are exposed as safe functions; they return no customer data.
create or replace function public.is_camera_available(
  p_camera_id bigint,
  p_date date,
  p_plan text,
  p_start_time time default '00:00',
  p_hours integer default 1
) returns boolean
language sql
security definer
set search_path = public
as $$
  select not exists (
    select 1 from public.orders o
    where o.camera_id = p_camera_id
      and o.status <> 'Hủy'
      and (o.customer->>'date')::date = p_date
      and (
        o.plan <> 'hourly' or p_plan <> 'hourly' or
        (
          (p_start_time < ((o.customer->>'startTime')::time + make_interval(mins => coalesce((o.customer->>'hours')::integer,1)*60)))
          and
          ((p_start_time + make_interval(mins => coalesce(p_hours,1)*60)) > (o.customer->>'startTime')::time)
        )
      )
  );
$$;

grant execute on function public.is_camera_available(bigint,date,text,time,integer) to anon, authenticated;

create or replace function public.get_available_camera_ids(
  p_date date,
  p_plan text,
  p_start_time time default '00:00',
  p_hours integer default 1
) returns table(id bigint)
language sql
security definer
set search_path = public
as $$
  select c.id
  from public.cameras c
  where c.available = true
    and public.is_camera_available(c.id, p_date, p_plan, p_start_time, p_hours);
$$;

grant execute on function public.get_available_camera_ids(date,text,time,integer) to anon, authenticated;
